feat(FEC-11611): [Web] Pass the program ID when sending a bookmark
kaltura/playkit-js-providers pull request #155
Opened 2021-11-04 11:35 UTC by JonathanTGold

### Description of the Changes

save the epgId from provider response 
pass it as program ID parameter when sending a bookmark

Solves FEC-11611

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-11-04 11:58 UTC, OrenMe commented on src/k-provider/ott/provider-parser.js
> +    if (mediaAsset.data.epgId) metaData.epgId = mediaAsset.data.epgId;
test?

2021-11-04 12:09 UTC, yairans commented on src/k-provider/ott/provider-parser.js
> +    if (mediaAsset.data.recordingId) metaData.epgId = mediaAsset.data.recordingId;
```suggestion
    if (mediaAsset.data.recordingId) metaData.recordingId = mediaAsset.data.recordingId;
```
right? also need to add to the type

2021-11-04 14:59 UTC, JonathanTGold commented on src/k-provider/ott/provider-parser.js
> +    if (mediaAsset.data.epgId) metaData.epgId = mediaAsset.data.epgId;
yes

2021-11-04 15:36 UTC, yairans commented on flow-typed/types/media-config-metadata.js
> +  epgId?: string
add recordingId, mediaType, metas and tags

2021-11-07 09:30 UTC, yairans commented on flow-typed/types/media-config-metadata.js
> +  mediaType: string,
all of these have to be optionals

2021-11-07 12:36 UTC, yairans commented on flow-typed/types/media-config-metadata.js
> +  tags: Object,
tags are also optionals no?

2021-11-07 17:17 UTC, yairans submitted a review, later dismissed

2021-11-08 06:59 UTC, OrenMe requested changes

2021-11-08 06:59 UTC, OrenMe commented on src/k-provider/ott/services/bookmark/bookmark-service.js
> +    this._logger.debug('the processed bookmark', bookmarkServiceParams);
what does it mean? let's have more meaningful debug output.
For example: `bookmark added ${bookmarkServiceParams }`

2021-11-08 07:04 UTC, OrenMe approved these changes

2021-11-08 11:26 UTC, merged